"use client";
import { useEffect,useMemo,useState } from "react";
import { ImagePlus,Plus,Search,Settings2 } from "lucide-react";
import { asset,money,productionApi,uploadProductionImage } from "./production-api";

type Supplier={id:string;code:string;name:string;phone?:string|null};
type Item={id:string;code:string;name:string;typeName:string;imageUrl?:string|null;unit:string;stockQty:number;unitPrice?:number|null;supplierId?:string|null;note?:string|null};
const TYPES=["Cúc","Mác Cổ","Mác Gáy","Mác Sườn","Mác Size","Khóa Kéo","Chun","Dây Rút","Mex","Túi Nylon","Tem Barcode","Thùng Carton","Chỉ May","Khác"];
const UNITS=[["PIECE","Cái"],["METER","Mét"],["ROLL","Cuộn"],["SET","Bộ"],["KG","Kg"],["PACK","Gói"],["BOX","Hộp"],["OTHER","Khác"]];

export default function AccessoriesPageClient(){
 const [items,setItems]=useState<Item[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]);const [q,setQ]=useState("");const [editing,setEditing]=useState<Item|null|undefined>(undefined);const [supplierOpen,setSupplierOpen]=useState(false);const [error,setError]=useState("");
 async function load(){try{setError("");const [a,s]=await Promise.all([productionApi<Item[]>("/production/accessories"),productionApi<Supplier[]>("/production/accessory-suppliers")]);setItems(a);setSuppliers(s)}catch(e){setError(e instanceof Error?e.message:"Không tải được NPL.")}}
 useEffect(()=>{void load()},[]);
 const rows=useMemo(()=>{const k=q.trim().toLowerCase();return k?items.filter(x=>[x.code,x.name,x.typeName].some(v=>String(v).toLowerCase().includes(k))):items},[items,q]);
 return <div className="space-y-5">
   <div className="flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.16em] text-neutral-400">Sản xuất</div><h1 className="mt-1 text-2xl font-semibold">Nguyên phụ liệu</h1><p className="mt-1 text-sm text-neutral-500">Quản lý cúc, mác, khóa, chun, bao bì, tồn và NCC NPL.</p></div><div className="flex gap-2"><button onClick={()=>setSupplierOpen(true)} className="rounded-2xl border px-4 py-2.5 text-sm font-semibold"><Settings2 className="mr-2 inline h-4 w-4"/>NCC NPL</button><button onClick={()=>setEditing(null)} className="rounded-2xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="mr-1 inline h-4 w-4"/>Thêm NPL</button></div></div>
   {error&&<Err x={error}/>}
   <div className="rounded-3xl border bg-white p-4 shadow-sm"><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-neutral-400"/><input className="w-full rounded-2xl border py-2.5 pl-10 pr-3 text-sm" value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm mã, tên, loại..."/></div></div>
   <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(x=><div key={x.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex gap-4 p-4"><div className="h-24 w-24 overflow-hidden rounded-2xl bg-neutral-100">{x.imageUrl?<img src={asset(x.imageUrl)} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-2xl text-neutral-300">✦</div>}</div><div className="min-w-0 flex-1"><div className="text-xs font-semibold text-neutral-400">{x.code} · {x.typeName}</div><div className="mt-1 text-lg font-semibold">{x.name}</div><div className="mt-2 text-sm">Tồn: <b>{Number(x.stockQty||0).toLocaleString("vi-VN")}</b> {UNITS.find(u=>u[0]===x.unit)?.[1]||x.unit}</div><div className="text-xs text-neutral-400">{x.unitPrice?money(x.unitPrice):"Chưa có giá"}</div></div></div><div className="flex justify-end border-t p-3"><button onClick={()=>setEditing(x)} className="rounded-xl border px-3 py-2 text-xs font-semibold">Mở / sửa</button></div></div>)}</div>
   {!rows.length&&<div className="rounded-3xl border bg-white p-12 text-center text-sm text-neutral-400">Chưa có nguyên phụ liệu.</div>}
   {editing!==undefined&&<ItemModal item={editing} suppliers={suppliers} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await load()}}/>}
   {supplierOpen&&<SupplierModal rows={suppliers} onClose={()=>setSupplierOpen(false)} onSaved={load}/>}
 </div>
}
function ItemModal({item,suppliers,onClose,onSaved}:{item:Item|null;suppliers:Supplier[];onClose:()=>void;onSaved:()=>void}){
 const [f,setF]=useState<any>({code:item?.code||"",name:item?.name||"",typeName:item?.typeName||"Cúc",imageUrl:item?.imageUrl||"",unit:item?.unit||"PIECE",stockQty:item?.stockQty??0,unitPrice:item?.unitPrice??"",supplierId:item?.supplierId||"",note:item?.note||""});const [error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function up(file:File){try{const r=await uploadProductionImage(file);setF({...f,imageUrl:r.url})}catch(e){setError(e instanceof Error?e.message:"Upload lỗi")}}
 async function save(){try{setSaving(true);setError("");await productionApi(item?`/production/accessories/${item.id}`:"/production/accessories",{method:item?"PATCH":"POST",body:JSON.stringify(f)});onSaved()}catch(e){setError(e instanceof Error?e.message:"Không lưu được.")}finally{setSaving(false)}}
 return <Modal title={item?`Sửa ${item.code}`:"Thêm nguyên phụ liệu"} onClose={onClose}><div className="space-y-4 p-5">{error&&<Err x={error}/>}<div className="grid gap-4 md:grid-cols-2"><Field l="Mã NPL"><input className={input} value={f.code} onChange={e=>setF({...f,code:e.target.value})} placeholder="Tự sinh nếu trống"/></Field><Field l="Tên NPL"><input className={input} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field l="Loại"><select className={input} value={f.typeName} onChange={e=>setF({...f,typeName:e.target.value})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field l="Đơn vị"><select className={input} value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}>{UNITS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></Field><Field l="Tồn"><input type="number" className={input} value={f.stockQty} onChange={e=>setF({...f,stockQty:e.target.value})}/></Field><Field l="Đơn giá"><input type="number" className={input} value={f.unitPrice} onChange={e=>setF({...f,unitPrice:e.target.value})}/></Field><Field l="NCC NPL"><select className={input} value={f.supplierId} onChange={e=>setF({...f,supplierId:e.target.value})}><option value="">Chưa chọn</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></Field></div><div className="rounded-2xl border border-dashed p-4"><div className="flex justify-between"><b className="text-sm">Ảnh đại diện</b><label className="cursor-pointer rounded-xl bg-neutral-950 px-3 py-2 text-xs font-semibold text-white"><ImagePlus className="mr-1 inline h-4 w-4"/>Tải ảnh<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&void up(e.target.files[0])}/></label></div>{f.imageUrl&&<img src={asset(f.imageUrl)} className="mt-3 h-36 rounded-2xl object-cover"/>}</div><Field l="Ghi chú"><textarea className={`${input} min-h-20`} value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></Field><button disabled={saving} onClick={()=>void save()} className="w-full rounded-xl bg-neutral-950 py-3 font-semibold text-white">{saving?"Đang lưu...":"Lưu NPL"}</button></div></Modal>
}
function SupplierModal({rows,onClose,onSaved}:{rows:Supplier[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({name:"",code:"",phone:""}),[error,setError]=useState("");async function save(){try{await productionApi("/production/accessory-suppliers",{method:"POST",body:JSON.stringify(f)});setF({name:"",code:"",phone:""});await onSaved()}catch(e){setError(e instanceof Error?e.message:"Không tạo được NCC.")}}return <Modal title="NCC nguyên phụ liệu" onClose={onClose}><div className="grid gap-5 p-5 md:grid-cols-2"><div className="max-h-96 overflow-y-auto rounded-2xl border">{rows.map(s=><div key={s.id} className="border-b p-3 text-sm"><b>{s.code} · {s.name}</b><div className="text-xs text-neutral-400">{s.phone||""}</div></div>)}</div><div className="space-y-3">{error&&<Err x={error}/>}<Field l="Tên NCC"><input className={input} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field l="Mã"><input className={input} value={f.code} onChange={e=>setF({...f,code:e.target.value})} placeholder="Tự sinh nếu trống"/></Field><Field l="SĐT"><input className={input} value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></Field><button onClick={()=>void save()} className="w-full rounded-xl bg-neutral-950 py-2.5 font-semibold text-white">Tạo NCC</button></div></div></Modal>}
const input="w-full rounded-2xl border border-neutral-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-neutral-900";
function Field({l,children}:{l:string;children:any}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-neutral-500">{l}</span>{children}</label>}
function Err({x}:{x:string}){return <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{x}</div>}
function Modal({title,children,onClose}:{title:string;children:any;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/40 p-4"><div className="w-full max-w-4xl rounded-3xl bg-white shadow-2xl"><div className="flex justify-between border-b px-5 py-4"><h2 className="font-semibold">{title}</h2><button onClick={onClose} className="h-9 w-9 rounded-xl border">×</button></div>{children}</div></div>}
