"use client";
import MobileBottomNav from "@/components/mobile/MobileBottomNav";
import { apiJson } from "@/lib/api";
import { API_BASE } from "@/lib/api-base";
import { ArrowLeft,Layers3,Search,X } from "lucide-react";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";

async function api<T=any>(p:string){return apiJson<T>(p,{redirectOnUnauthorized:false} as any)}
function asset(u?:string|null){if(!u)return "";return /^https?:\/\//.test(u)?u:`${API_BASE}${u.startsWith("/")?"":"/"}${u}`}

export default function Page(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(""),[detail,setDetail]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{api<any[]>("/sample-fabric/library").then(setRows).catch(e=>setError(e.message))},[]);
 const list=useMemo(()=>{const k=q.trim().toLowerCase();return k?rows.filter(x=>[x.boardCode,x.fabricCode,x.name,x.composition].some(v=>String(v||"").toLowerCase().includes(k))):rows},[rows,q]);
 return <main className="min-h-[100dvh] bg-neutral-100 pb-[calc(112px+env(safe-area-inset-bottom))]"><div className="mx-auto max-w-md"><header className="sticky top-0 z-20 border-b bg-white px-4 pb-4 pt-[calc(16px+env(safe-area-inset-top))]"><div className="flex items-center gap-3"><Link href="/mobile/production" className="grid h-10 w-10 place-items-center rounded-full bg-neutral-100"><ArrowLeft className="h-5 w-5"/></Link><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-neutral-400">Nguyên liệu</div><h1 className="text-xl font-black">Bảng vải</h1></div></div><div className="relative mt-4"><Search className="absolute left-3 top-3.5 h-4 w-4 text-neutral-400"/><input className="w-full rounded-2xl border bg-white py-3 pl-10 pr-3 text-base" value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm mã bảng, mã vải, thành phần..."/></div></header><div className="space-y-3 p-4">{error&&<div className="rounded-2xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{list.map(b=>{const image=asset(b.images?.[0]?.url);return <button key={b.id} onClick={()=>setDetail(b)} className="flex w-full gap-3 rounded-[26px] bg-white p-4 text-left shadow-sm"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-2xl bg-neutral-100">{image?<img src={image} className="h-full w-full object-cover" alt=""/>:<div className="grid h-full place-items-center"><Layers3 className="h-7 w-7 text-neutral-300"/></div>}</div><div><div className="text-xs font-black text-neutral-400">{b.boardCode}</div><div className="mt-1 font-black">{b.name||b.fabricCode||"Bảng vải"}</div><div className="mt-2 text-xs text-neutral-500">{b.composition||"Chưa có thành phần"}</div></div></button>})}</div></div>{detail&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/45 p-3"><div className="mx-auto my-4 max-w-md rounded-[30px] bg-white p-4"><div className="flex justify-between"><div><div className="text-xs font-black text-neutral-400">{detail.boardCode}</div><div className="text-lg font-black">{detail.name||detail.fabricCode}</div></div><button onClick={()=>setDetail(null)} className="grid h-10 w-10 place-items-center rounded-full border"><X className="h-4 w-4"/></button></div><div className="mt-4 grid grid-cols-2 gap-3"><I l="Mã chất vải" v={detail.fabricCode||"—"}/><I l="GSM" v={detail.gsm||"—"}/><I l="Thành phần" v={detail.composition||"—"}/><I l="NCC" v={detail.supplier?.code||detail.supplier?.name||"—"}/></div><div className="mt-4"><b className="text-sm">Mùa phù hợp</b><div className="mt-2 flex flex-wrap gap-2">{detail.seasons?.map((x:string)=><span key={x} className="rounded-full bg-neutral-100 px-3 py-2 text-xs font-bold">{x}</span>)}</div></div><div className="mt-4"><b className="text-sm">Nhóm sản phẩm</b><div className="mt-2 flex flex-wrap gap-2">{detail.productGroups?.map((x:string)=><span key={x} className="rounded-full bg-neutral-100 px-3 py-2 text-xs font-bold">{x}</span>)}</div></div></div></div>}<MobileBottomNav/></main>
}
function I({l,v}:{l:string;v:any}){return <div className="rounded-2xl bg-neutral-50 p-3"><div className="text-[10px] font-bold uppercase text-neutral-400">{l}</div><div className="mt-1 text-sm font-black">{v}</div></div>}
