export const currentUser = { name: 'Admin The 1970', role: 'ADMIN' }

export const branches = [
  { id: 'b1', name: 'Hoàn Kiếm', code: 'HK' },
  { id: 'b2', name: 'Hai Bà Trưng', code: 'HBT' },
  { id: 'b3', name: 'Online Warehouse', code: 'OL' },
]

export const productGroups = [
  'T-Shirt',
  'Shirt',
  'Polo',
  'Outerwear',
  'Knitwear',
  'Accessories',
]

export const productTypes = [
  'Core',
  'New Arrival',
  'Best Seller',
  'Seasonal',
  'Limited',
]

export const brandOptions = [
  'The 1970',
  'The 1970 Heritage',
  'The 1970 Studio',
]

export const initialProducts = [
  {
    id: 'p1',
    name: 'QS794 Palm',
    slug: 'qs794-palm',
    category: 'T-Shirt',
    productType: 'Best Seller',
    brand: 'The 1970',
    weight: 220,
    imageUrl: 'https://placehold.co/600x600?text=QS794+Palm',
    status: 'ACTIVE',
    description: 'Áo phông The 1970 phom gọn, chất cotton dày đứng form.',
    variants: [
      {
        id: 'v1',
        sku: 'QS794-GREEN-S',
        color: 'Green',
        size: 'S',
        price: 390000,
        costPrice: 220000,
        stock: 12,
        branchStocks: { b1: 4, b2: 3, b3: 5 },
      },
      {
        id: 'v2',
        sku: 'QS794-GREEN-M',
        color: 'Green',
        size: 'M',
        price: 390000,
        costPrice: 220000,
        stock: 8,
        branchStocks: { b1: 2, b2: 2, b3: 4 },
      },
      {
        id: 'v3',
        sku: 'QS794-GREEN-L',
        color: 'Green',
        size: 'L',
        price: 390000,
        costPrice: 220000,
        stock: 4,
        branchStocks: { b1: 1, b2: 1, b3: 2 },
      },
    ],
  },
  {
    id: 'p2',
    name: 'SM902 Rêu Đen',
    slug: 'sm902-reu-den',
    category: 'Shirt',
    productType: 'Core',
    brand: 'The 1970',
    weight: 340,
    imageUrl: 'https://placehold.co/600x600?text=SM902+Reu+Den',
    status: 'ACTIVE',
    description: 'Sơ mi flannel mềm ấm, màu rêu đen trầm nam tính.',
    variants: [
      {
        id: 'v4',
        sku: 'SM902-REUDEN-M',
        color: 'Rêu Đen',
        size: 'M',
        price: 620000,
        costPrice: 360000,
        stock: 7,
        branchStocks: { b1: 2, b2: 2, b3: 3 },
      },
      {
        id: 'v5',
        sku: 'SM902-REUDEN-L',
        color: 'Rêu Đen',
        size: 'L',
        price: 620000,
        costPrice: 360000,
        stock: 5,
        branchStocks: { b1: 1, b2: 1, b3: 3 },
      },
    ],
  },
  {
    id: 'p3',
    name: 'Heritage Tee Tobacco',
    slug: 'heritage-tee-tobacco',
    category: 'T-Shirt',
    productType: 'New Arrival',
    brand: 'The 1970 Heritage',
    weight: 240,
    imageUrl: 'https://placehold.co/600x600?text=Heritage+Tee',
    status: 'ACTIVE',
    description: 'Dòng heritage với bo cổ contrast, vibe classic American.',
    variants: [
      {
        id: 'v6',
        sku: 'HTB-TOBACCO-S',
        color: 'Tobacco',
        size: 'S',
        price: 450000,
        costPrice: 260000,
        stock: 2,
        branchStocks: { b1: 1, b2: 0, b3: 1 },
      },
      {
        id: 'v7',
        sku: 'HTB-TOBACCO-M',
        color: 'Tobacco',
        size: 'M',
        price: 450000,
        costPrice: 260000,
        stock: 1,
        branchStocks: { b1: 0, b2: 0, b3: 1 },
      },
    ],
  },
]

export const initialOrders = [
  {
    id: 'o1',
    orderCode: 'ORD-1774A',
    createdAt: '2026-03-25 09:20',
    salesChannel: 'VN_WEB',
    paymentStatus: 'AWAITING_PAYMENT',
    orderStatus: 'PENDING',
    customerName: 'Khách lẻ web',
    customerPhone: '0988 111 222',
    branchId: 'b3',
    note: 'Test đơn từ web riêng',
    grandTotal: 780000,
    items: [
      {
        variantId: 'v1',
        sku: 'QS794-GREEN-S',
        productName: 'QS794 Palm',
        color: 'Green',
        size: 'S',
        qty: 2,
        unitPrice: 390000,
        lineTotal: 780000,
      },
    ],
  },
  {
    id: 'o2',
    orderCode: 'ORD-1774B',
    createdAt: '2026-03-25 10:05',
    salesChannel: 'ADMIN',
    paymentStatus: 'PAID',
    orderStatus: 'CONFIRMED',
    customerName: 'Nguyễn Minh',
    customerPhone: '0903 222 888',
    branchId: 'b1',
    note: 'Đơn tạo tay tại shop',
    grandTotal: 620000,
    items: [
      {
        variantId: 'v4',
        sku: 'SM902-REUDEN-M',
        productName: 'SM902 Rêu Đen',
        color: 'Rêu Đen',
        size: 'M',
        qty: 1,
        unitPrice: 620000,
        lineTotal: 620000,
      },
    ],
  },
  {
    id: 'o3',
    orderCode: 'ORD-1774C',
    createdAt: '2026-03-25 11:10',
    salesChannel: 'FACEBOOK',
    paymentStatus: 'PENDING_COD',
    orderStatus: 'PROCESSING',
    customerName: 'Trần Hoàng',
    customerPhone: '0912 333 666',
    branchId: 'b2',
    note: 'Ship hỏa tốc nội thành',
    grandTotal: 900000,
    items: [
      {
        variantId: 'v6',
        sku: 'HTB-TOBACCO-S',
        productName: 'Heritage Tee Tobacco',
        color: 'Tobacco',
        size: 'S',
        qty: 2,
        unitPrice: 450000,
        lineTotal: 900000,
      },
    ],
  },
]

export const initialStocktakes = [
  {
    id: 'st1',
    branchId: 'b1',
    createdAt: '2026-03-25 08:30',
    status: 'IN_PROGRESS',
    note: 'Kiểm nhanh đầu ngày',
    lines: [
      { sku: 'QS794-GREEN-S', systemStock: 4, countedStock: 4, diff: 0 },
    ],
  },
  {
    id: 'st2',
    branchId: 'b3',
    createdAt: '2026-03-24 18:10',
    status: 'COMPLETED',
    note: 'Chốt kho cuối ngày',
    lines: [
      {
        sku: 'SM902-REUDEN-L',
        systemStock: 3,
        countedStock: 2,
        diff: -1,
        reason: 'Thiếu hàng thực tế',
      },
    ],
  },
]

export const roleTemplates = [
  {
    id: 'admin',
    name: 'Admin / Owner',
    scope: 'ALL_BRANCHES',
    description: 'Toàn quyền hệ thống, nhìn được báo cáo và giá vốn.',
    activeEmployees: 1,
    inactiveEmployees: 0,
    createdAt: '07/08/2025',
    updatedAt: '18/03/2026',
    note: 'Owner',
    permissions: {
      products: [
        'Xem sản phẩm',
        'Tạo sản phẩm',
        'Thêm variant',
        'Đổi trạng thái sản phẩm',
        'Xem giá nhập',
        'Sửa giá nhập',
      ],
      orders: [
        'Xem tất cả đơn',
        'Tạo đơn hàng',
        'Sửa đơn hàng',
        'Duyệt đơn hàng',
        'Đẩy đơn sang hãng vận chuyển',
      ],
      inventory: [
        'Xem tồn kho toàn hệ thống',
        'Kiểm kho',
        'Xác nhận kiểm kho',
        'Nhập hàng',
        'Chuyển hàng giữa chi nhánh',
      ],
      reports: [
        'Xem báo cáo chi nhánh',
        'Xem báo cáo toàn hệ thống',
        'Xem lợi nhuận',
        'Xem ROAS thật',
      ],
      customers: ['Xem khách hàng'],
      system: ['Phân quyền vai trò', 'Cấu hình hệ thống'],
    },
  },
  {
    id: 'branch-manager',
    name: 'Quản lý chi nhánh',
    scope: 'ONE_BRANCH',
    description:
      'Quản lý vận hành của một chi nhánh, không thấy toàn hệ thống.',
    activeEmployees: 2,
    inactiveEmployees: 0,
    createdAt: '08/08/2025',
    updatedAt: '18/03/2026',
    note: 'Theo chi nhánh',
    permissions: {
      products: ['Xem sản phẩm', 'Tạo sản phẩm', 'Thêm variant'],
      orders: [
        'Xem đơn chi nhánh',
        'Tạo đơn hàng',
        'Sửa đơn hàng',
        'Duyệt đơn hàng',
        'Đẩy đơn sang hãng vận chuyển',
      ],
      inventory: [
        'Xem tồn kho chi nhánh',
        'Kiểm kho',
        'Xác nhận kiểm kho',
        'Nhập hàng',
        'Chuyển hàng',
      ],
      reports: ['Xem báo cáo chi nhánh'],
      customers: ['Xem khách hàng'],
      system: [],
    },
  },
  {
    id: 'fulltime',
    name: 'Nhân viên fulltime',
    scope: 'ONE_BRANCH',
    description:
      'Vận hành mạnh hơn bán lẻ, được xử lý đơn và đẩy sang hãng vận chuyển.',
    activeEmployees: 4,
    inactiveEmployees: 1,
    createdAt: '07/08/2025',
    updatedAt: '18/03/2026',
    note: 'Không xem báo cáo',
    permissions: {
      products: ['Xem sản phẩm'],
      orders: [
        'Xem đơn chi nhánh',
        'Tạo đơn hàng',
        'Sửa đơn hàng',
        'Đẩy đơn sang hãng vận chuyển',
      ],
      inventory: ['Xem tồn kho chi nhánh', 'Kiểm kho', 'Nhập hàng', 'Chuyển hàng'],
      reports: [],
      customers: ['Xem khách hàng'],
      system: [],
    },
  },
  {
    id: 'retail-staff',
    name: 'Nhân viên bán lẻ',
    scope: 'ONE_BRANCH',
    description:
      'Tập trung bán hàng tại quầy, quyền gọn và an toàn hơn fulltime.',
    activeEmployees: 13,
    inactiveEmployees: 0,
    createdAt: '07/08/2025',
    updatedAt: '05/12/2025',
    note: 'Không xem báo cáo, không đụng kho',
    permissions: {
      products: ['Xem sản phẩm'],
      orders: ['Xem đơn được phụ trách', 'Tạo đơn hàng'],
      inventory: ['Xem tồn kho chi nhánh'],
      reports: [],
      customers: ['Xem khách hàng'],
      system: [],
    },
  },
  {
    id: 'stock-auditor',
    name: 'Nhân viên kiểm kho',
    scope: 'ONE_BRANCH',
    description: 'Chỉ tập trung kiểm kho và đối chiếu tồn.',
    activeEmployees: 1,
    inactiveEmployees: 1,
    createdAt: '07/08/2025',
    updatedAt: '18/03/2026',
    note: 'Không xử lý đơn bán',
    permissions: {
      products: ['Xem sản phẩm'],
      orders: [],
      inventory: ['Xem tồn kho chi nhánh', 'Kiểm kho'],
      reports: [],
      customers: [],
      system: [],
    },
  },
]

export const initialEmployees = [
  {
    id: 'u1',
    name: 'Anh Kiều',
    code: 'NV001',
    status: 'WORKING',
    roleId: 'admin',
    branchIds: ['b1', 'b2', 'b3'],
  },
  {
    id: 'u2',
    name: 'Mai Anh',
    code: 'NV014',
    status: 'WORKING',
    roleId: 'branch-manager',
    branchIds: ['b1'],
  },
  {
    id: 'u3',
    name: 'Tuấn HBT',
    code: 'NV021',
    status: 'WORKING',
    roleId: 'branch-manager',
    branchIds: ['b2'],
  },
  {
    id: 'u4',
    name: 'Quỳnh QQ',
    code: 'NV031',
    status: 'WORKING',
    roleId: 'fulltime',
    branchIds: ['b1'],
  },
  {
    id: 'u5',
    name: 'Phương HK',
    code: 'NV032',
    status: 'WORKING',
    roleId: 'fulltime',
    branchIds: ['b1'],
  },
  {
    id: 'u6',
    name: 'Lan HBT',
    code: 'NV033',
    status: 'WORKING',
    roleId: 'fulltime',
    branchIds: ['b2'],
  },
  {
    id: 'u7',
    name: 'Minh OL',
    code: 'NV034',
    status: 'WORKING',
    roleId: 'fulltime',
    branchIds: ['b3'],
  },
  {
    id: 'u8',
    name: 'Ngọc Store',
    code: 'NV041',
    status: 'WORKING',
    roleId: 'retail-staff',
    branchIds: ['b1'],
  },
  {
    id: 'u9',
    name: 'Hà Store',
    code: 'NV042',
    status: 'WORKING',
    roleId: 'retail-staff',
    branchIds: ['b1'],
  },
  {
    id: 'u10',
    name: 'Linh Store',
    code: 'NV043',
    status: 'WORKING',
    roleId: 'retail-staff',
    branchIds: ['b2'],
  },
  {
    id: 'u11',
    name: 'Dũng Kho',
    code: 'NV051',
    status: 'WORKING',
    roleId: 'stock-auditor',
    branchIds: ['b3'],
  },
  {
    id: 'u12',
    name: 'Cường Cũ',
    code: 'NV099',
    status: 'INACTIVE',
    roleId: 'fulltime',
    branchIds: ['b1'],
  },
]

export const permissionGroups = [
  { key: 'products', label: 'Sản phẩm' },
  { key: 'orders', label: 'Đơn hàng' },
  { key: 'inventory', label: 'Kho vận hành' },
  { key: 'reports', label: 'Báo cáo' },
  { key: 'customers', label: 'Khách hàng' },
  { key: 'system', label: 'Hệ thống' },
]

export const permissionGroupDescriptions: Record<string, string> = {
  products: 'Ai được xem, tạo và can thiệp dữ liệu sản phẩm.',
  orders: 'Ai được tạo, sửa, duyệt và đẩy đơn sang hãng vận chuyển.',
  inventory: 'Ai được xem tồn, kiểm kho, nhập hàng và chuyển hàng.',
  reports: 'Ai được xem báo cáo chi nhánh hoặc toàn hệ thống.',
  customers: 'Ai được truy cập dữ liệu khách hàng.',
  system: 'Ai được phân quyền và cấu hình hệ thống.',
}

export const initialAdsMappings = [
  {
    id: 'm1',
    sku: 'QS794-GREEN-S',
    productName: 'QS794 Palm',
    campaignName: 'QS794 Palm Conversion',
    campaignId: 'cmp_1970_001',
    adsetName: 'QS794 Green Core',
    adsetId: 'adset_1970_001',
    channel: 'FACEBOOK',
    status: 'CONNECTED',
    spendToday: 850000,
    revenueToday: 2860000,
    roasToday: 3.36,
    budgetDaily: 1200000,
    lastAction: 'Không có',
  },
  {
    id: 'm2',
    sku: 'SM902-REUDEN-M',
    productName: 'SM902 Rêu Đen',
    campaignName: 'SM902 Traffic to Purchase',
    campaignId: 'cmp_1970_002',
    adsetName: 'SM902 Broad',
    adsetId: 'adset_1970_002',
    channel: 'FACEBOOK',
    status: 'CONNECTED',
    spendToday: 430000,
    revenueToday: 620000,
    roasToday: 1.44,
    budgetDaily: 800000,
    lastAction: 'Giữ nguyên',
  },
  {
    id: 'm3',
    sku: 'HTB-TOBACCO-S',
    productName: 'Heritage Tee Tobacco',
    campaignName: 'Heritage Tee Launch',
    campaignId: 'cmp_1970_003',
    adsetName: 'Heritage Tee Interest',
    adsetId: 'adset_1970_003',
    channel: 'FACEBOOK',
    status: 'NEEDS_MAPPING',
    spendToday: 0,
    revenueToday: 0,
    roasToday: 0,
    budgetDaily: 0,
    lastAction: 'Chưa map',
  },
]