"use client";
import MobileBottomNav from "@/components/mobile/MobileBottomNav";
import { apiJson } from "@/lib/api";
import { getMobileToken } from "@/lib/mobile-auth-token";
import Link from "next/link";
import { Factory,Scissors,Shirt } from "lucide-react";
import { useEffect,useState } from "react";
async function api<T=any>(p:string){await getMobileToken();return apiJson<T>(p,{redirectOnUnauthorized:false} as any)}
export default function Page(){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState("");useEffect(()=>{api<any[]>("/production/orders").then(setRows).catch(e=>setError(e.message))},[]);return <div className="min-h-screen bg-neutral-100 pb-28"><div className="mx-auto max-w-md"><header className="border-b bg-white px-4 pb-4 pt-5"><div className="text-xs font-bold uppercase text-neutral-400">Sản xuất</div><h1 className="text-xl font-black">Trung tâm sản xuất</h1></header><main className="space-y-4 p-4"><div className="grid grid-cols-2 gap-3"><Link href="/mobile/samples" className="rounded-3xl bg-neutral-950 p-4 text-white"><Shirt className="h-6 w-6"/><div className="mt-4 font-black">Tạo mẫu nhanh</div><div className="text-xs text-neutral-300">2 ảnh, lưu ngay</div></Link><Link href="/mobile/fabric" className="rounded-3xl bg-white p-4 shadow-sm"><Scissors className="h-6 w-6"/><div className="mt-4 font-black">Vải về</div><div className="text-xs text-neutral-400">Cây, màu, ảnh</div></Link></div>{error&&<div className="rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div><b>Lệnh SX gần đây</b><div className="mt-2 space-y-2">{rows.map(o=><div key={o.id} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex justify-between"><div><b>{o.code}</b><div className="text-sm">{o.sample?.code} · {o.sample?.name}</div></div><Factory className="h-5 w-5 text-neutral-400"/></div><div className="mt-1 text-xs text-neutral-500">{o.factory?.name||"—"} · {o.status}</div></div>)}</div></div></main></div><MobileBottomNav/></div>}
